import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/image.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import { motion } from 'framer-motion';
import HireMe from '@/components/HireMe'
import BannerImageSweeper from '../components/main_banner_component/banner_image_sweeper';

export default function Home() {
  return (
    <>
      <Head>
        <title>CEYLON ENHANCE</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center w-full min-h-screen text-dark dark:text-light '>
        <Layout className='pt-0 mt-4 md:pt-16 sm:pt-8 sm:mt-32 xs:mt-16 md:mt-16'>
          <div className='flex items-center justify-between w-full lg:flex-col gap-x-10 lg:gap-y-5 my-4 mx-4'>
            <div className='banner_size'>
              <BannerImageSweeper></BannerImageSweeper>
            </div>
            <div className='flex flex-col items-center self-center w-1/2 lg:w-full lg:text-center'>
              <AnimatedText text="Capture moments, create memories." className='!text-6xl !text-left
              xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl  sm:!text-3xl'/>
              <p className='my-4 text-base font-medium md:text-small sm:text-xs'>A passionate photographer dedicated to capturing the essence of life precious moments.
                With a keen eye for detail and a love for storytelling, I strive to create timeless images that evoke emotion and inspire wonder
              </p>

              
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href='#' target={'_blank'}
                className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-sm font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base'
                >My_Works <LinkArrow className={"w-6 ml-1"}/>
                </Link>


                <Link href='#' target={'_blank'}
                className='ml-4 text-lg font-medium underline capitalize text-dark dark:text-light md:text-base'>Contact</Link>
              </div>
            </div>
            
            
          </div>
        </Layout>
        <HireMe/>
      </main>
    </>
  )
}